import { createLab } from './index'
import * as components from './components'
import configuration from './components/vuelab-configs/index.js'
import { iconComponents } from './components/icons/index.js'
import iconConfig from './components/vuelab-configs/Icon.vuelab.js'

const colorOptions = [
  { id: 'neutral-50', name: '50', value: '#F4F7FA', group: 'Primary Colors', colorGroupName: 'neutral' },
  { id: 'neutral-100', name: '100', value: '#EFF2F5', group: 'Primary Colors', colorGroupName: 'neutral' },
  { id: 'neutral-200', name: '200', value: '#DEE4EB', group: 'Primary Colors', colorGroupName: 'neutral' },
  { id: 'neutral-300', name: '300', value: '#C3CCD6', group: 'Primary Colors', colorGroupName: 'neutral' },
  { id: 'neutral-400', name: '400', value: '#A8B5C2', group: 'Primary Colors', colorGroupName: 'neutral' },
  { id: 'neutral-500', name: '500', value: '#8593A3', group: 'Primary Colors', colorGroupName: 'neutral', isBase: true },
  { id: 'neutral-600', name: '600', value: '#6A7682', group: 'Primary Colors', colorGroupName: 'neutral' },
  { id: 'neutral-700', name: '700', value: '#505862', group: 'Primary Colors', colorGroupName: 'neutral' },
  { id: 'neutral-800', name: '800', value: '#353B41', group: 'Primary Colors', colorGroupName: 'neutral' },
  { id: 'neutral-900', name: '900', value: '#1B1D21', group: 'Primary Colors', colorGroupName: 'neutral' },

  { id: 'primary-50', name: '50', value: '#EEF0FD', group: 'Primary Colors', colorGroupName: 'primary' },
  { id: 'primary-100', name: '100', value: '#DEE1FD', group: 'Primary Colors', colorGroupName: 'primary' },
  { id: 'primary-200', name: '200', value: '#BCC4FB', group: 'Primary Colors', colorGroupName: 'primary' },
  { id: 'primary-300', name: '300', value: '#9BA6F9', group: 'Primary Colors', colorGroupName: 'primary' },
  { id: 'primary-400', name: '400', value: '#7E8CF7', group: 'Primary Colors', colorGroupName: 'primary' },
  { id: 'primary-500', name: '500', value: '#586AF5', group: 'Primary Colors', colorGroupName: 'primary', isBase: true },
  { id: 'primary-600', name: '600', value: '#3F4EC4', group: 'Primary Colors', colorGroupName: 'primary' },
  { id: 'primary-700', name: '700', value: '#293593', group: 'Primary Colors', colorGroupName: 'primary' },
  { id: 'primary-800', name: '800', value: '#182062', group: 'Primary Colors', colorGroupName: 'primary' },
  { id: 'primary-900', name: '900', value: '#0A0E31', group: 'Primary Colors', colorGroupName: 'primary' },

  { id: 'success-50', name: '50', value: '#E6FAF4', group: 'Primary Colors', colorGroupName: 'success' },
  { id: 'success-100', name: '100', value: '#D4F4EC', group: 'Primary Colors', colorGroupName: 'success' },
  { id: 'success-200', name: '200', value: '#A9EAD8', group: 'Primary Colors', colorGroupName: 'success' },
  { id: 'success-300', name: '300', value: '#7EDFC5', group: 'Primary Colors', colorGroupName: 'success' },
  { id: 'success-400', name: '400', value: '#53D5B2', group: 'Primary Colors', colorGroupName: 'success' },
  { id: 'success-500', name: '500', value: '#28CA9E', group: 'Primary Colors', colorGroupName: 'success', isBase: true },
  { id: 'success-600', name: '600', value: '#20A17F', group: 'Primary Colors', colorGroupName: 'success' },
  { id: 'success-700', name: '700', value: '#18795F', group: 'Primary Colors', colorGroupName: 'success' },
  { id: 'success-800', name: '800', value: '#10513F', group: 'Primary Colors', colorGroupName: 'success' },
  { id: 'success-900', name: '900', value: '#082820', group: 'Primary Colors', colorGroupName: 'success' },

  { id: 'warning-50', name: '50', value: '#FFF7E5', group: 'Primary Colors', colorGroupName: 'warning' },
  { id: 'warning-100', name: '100', value: '#FEC', group: 'Primary Colors', colorGroupName: 'warning' },
  { id: 'warning-200', name: '200', value: '#FD9', group: 'Primary Colors', colorGroupName: 'warning' },
  { id: 'warning-300', name: '300', value: '#FFCD66', group: 'Primary Colors', colorGroupName: 'warning' },
  { id: 'warning-400', name: '400', value: '#FFBC33', group: 'Primary Colors', colorGroupName: 'warning' },
  { id: 'warning-500', name: '500', value: '#FFAB00', group: 'Primary Colors', colorGroupName: 'warning', isBase: true },
  { id: 'warning-600', name: '600', value: '#CC7A00', group: 'Primary Colors', colorGroupName: 'warning' },
  { id: 'warning-700', name: '700', value: '#995200', group: 'Primary Colors', colorGroupName: 'warning' },
  { id: 'warning-800', name: '800', value: '#663000', group: 'Primary Colors', colorGroupName: 'warning' },
  { id: 'warning-900', name: '900', value: '#331400', group: 'Primary Colors', colorGroupName: 'warning' },

  { id: 'error-50', name: '50', value: '#FDF1ED', group: 'Primary Colors', colorGroupName: 'error' },
  { id: 'error-100', name: '100', value: '#FDDDD3', group: 'Primary Colors', colorGroupName: 'error' },
  { id: 'error-200', name: '200', value: '#FABBA8', group: 'Primary Colors', colorGroupName: 'error' },
  { id: 'error-300', name: '300', value: '#F89A7C', group: 'Primary Colors', colorGroupName: 'error' },
  { id: 'error-400', name: '400', value: '#F57851', group: 'Primary Colors', colorGroupName: 'error' },
  { id: 'error-500', name: '500', value: '#F35625', group: 'Primary Colors', colorGroupName: 'error', isBase: true },
  { id: 'error-600', name: '600', value: '#C2451E', group: 'Primary Colors', colorGroupName: 'error' },
  { id: 'error-700', name: '700', value: '#923416', group: 'Primary Colors', colorGroupName: 'error' },
  { id: 'error-800', name: '800', value: '#61220F', group: 'Primary Colors', colorGroupName: 'error' },
  { id: 'error-900', name: '900', value: '#311107', group: 'Primary Colors', colorGroupName: 'error' },

  { id: 'purple-50', name: '50', value: '#F6F3FF', group: 'Secondary Colors', colorGroupName: 'purple' },
  { id: 'purple-100', name: '100', value: '#E5DFFE', group: 'Secondary Colors', colorGroupName: 'purple' },
  { id: 'purple-200', name: '200', value: '#CBBEFD', group: 'Secondary Colors', colorGroupName: 'purple' },
  { id: 'purple-300', name: '300', value: '#B19EFC', group: 'Secondary Colors', colorGroupName: 'purple' },
  { id: 'purple-400', name: '400', value: '#977EFB', group: 'Secondary Colors', colorGroupName: 'purple' },
  { id: 'purple-500', name: '500', value: '#7D5EFA', group: 'Secondary Colors', colorGroupName: 'purple', isBase: true },
  { id: 'purple-600', name: '600', value: '#644BC8', group: 'Secondary Colors', colorGroupName: 'purple' },
  { id: 'purple-700', name: '700', value: '#4B3896', group: 'Secondary Colors', colorGroupName: 'purple' },
  { id: 'purple-800', name: '800', value: '#322564', group: 'Secondary Colors', colorGroupName: 'purple' },
  { id: 'purple-900', name: '900', value: '#191332', group: 'Secondary Colors', colorGroupName: 'purple' },

  { id: 'blue-50', name: '50', value: '#EEF6FF', group: 'Secondary Colors', colorGroupName: 'blue' },
  { id: 'blue-100', name: '100', value: '#D7EAFF', group: 'Secondary Colors', colorGroupName: 'blue' },
  { id: 'blue-200', name: '200', value: '#AFD5FF', group: 'Secondary Colors', colorGroupName: 'blue' },
  { id: 'blue-300', name: '300', value: '#87C0FF', group: 'Secondary Colors', colorGroupName: 'blue' },
  { id: 'blue-400', name: '400', value: '#5EACFF', group: 'Secondary Colors', colorGroupName: 'blue' },
  { id: 'blue-500', name: '500', value: '#3697FF', group: 'Secondary Colors', colorGroupName: 'blue', isBase: true },
  { id: 'blue-600', name: '600', value: '#2B79CC', group: 'Secondary Colors', colorGroupName: 'blue' },
  { id: 'blue-700', name: '700', value: '#215A99', group: 'Secondary Colors', colorGroupName: 'blue' },
  { id: 'blue-800', name: '800', value: '#163C66', group: 'Secondary Colors', colorGroupName: 'blue' },
  { id: 'blue-900', name: '900', value: '#0B1E33', group: 'Secondary Colors', colorGroupName: 'blue' },

  { id: 'aqua-50', name: '50', value: '#EAFCFF', group: 'Secondary Colors', colorGroupName: 'aqua' },
  { id: 'aqua-100', name: '100', value: '#D2F4F9', group: 'Secondary Colors', colorGroupName: 'aqua' },
  { id: 'aqua-200', name: '200', value: '#A5E9F2', group: 'Secondary Colors', colorGroupName: 'aqua' },
  { id: 'aqua-300', name: '300', value: '#77DEEC', group: 'Secondary Colors', colorGroupName: 'aqua' },
  { id: 'aqua-400', name: '400', value: '#4AD3E5', group: 'Secondary Colors', colorGroupName: 'aqua' },
  { id: 'aqua-500', name: '500', value: '#1DC8DF', group: 'Secondary Colors', colorGroupName: 'aqua', isBase: true },
  { id: 'aqua-600', name: '600', value: '#17A0B2', group: 'Secondary Colors', colorGroupName: 'aqua' },
  { id: 'aqua-700', name: '700', value: '#117886', group: 'Secondary Colors', colorGroupName: 'aqua' },
  { id: 'aqua-800', name: '800', value: '#0C5059', group: 'Secondary Colors', colorGroupName: 'aqua' },
  { id: 'aqua-900', name: '900', value: '#06282D', group: 'Secondary Colors', colorGroupName: 'aqua' },

  { id: 'mint-50', name: '50', value: '#E9FFFC', group: 'Secondary Colors', colorGroupName: 'mint' },
  { id: 'mint-100', name: '100', value: '#D5F7F2', group: 'Secondary Colors', colorGroupName: 'mint' },
  { id: 'mint-200', name: '200', value: '#ABEFE6', group: 'Secondary Colors', colorGroupName: 'mint' },
  { id: 'mint-300', name: '300', value: '#81E7D9', group: 'Secondary Colors', colorGroupName: 'mint' },
  { id: 'mint-400', name: '400', value: '#57DECC', group: 'Secondary Colors', colorGroupName: 'mint' },
  { id: 'mint-500', name: '500', value: '#2DD6C0', group: 'Secondary Colors', colorGroupName: 'mint', isBase: true },
  { id: 'mint-600', name: '600', value: '#24AB99', group: 'Secondary Colors', colorGroupName: 'mint' },
  { id: 'mint-700', name: '700', value: '#1B8173', group: 'Secondary Colors', colorGroupName: 'mint' },
  { id: 'mint-800', name: '800', value: '#12564D', group: 'Secondary Colors', colorGroupName: 'mint' },
  { id: 'mint-900', name: '900', value: '#092B26', group: 'Secondary Colors', colorGroupName: 'mint' },

  { id: 'green-50', name: '50', value: '#E8FAF1', group: 'Secondary Colors', colorGroupName: 'green' },
  { id: 'green-100', name: '100', value: '#D3F6E4', group: 'Secondary Colors', colorGroupName: 'green' },
  { id: 'green-200', name: '200', value: '#A7ECCA', group: 'Secondary Colors', colorGroupName: 'green' },
  { id: 'green-300', name: '300', value: '#7BE3AF', group: 'Secondary Colors', colorGroupName: 'green' },
  { id: 'green-400', name: '400', value: '#4FDA95', group: 'Secondary Colors', colorGroupName: 'green' },
  { id: 'green-500', name: '500', value: '#24D07A', group: 'Secondary Colors', colorGroupName: 'green', isBase: true },
  { id: 'green-600', name: '600', value: '#1CA762', group: 'Secondary Colors', colorGroupName: 'green' },
  { id: 'green-700', name: '700', value: '#157D49', group: 'Secondary Colors', colorGroupName: 'green' },
  { id: 'green-800', name: '800', value: '#0E5331', group: 'Secondary Colors', colorGroupName: 'green' },
  { id: 'green-900', name: '900', value: '#072A18', group: 'Secondary Colors', colorGroupName: 'green' },

  { id: 'rose-50', name: '50', value: '#FFF0F4', group: 'Secondary Colors', colorGroupName: 'rose' },
  { id: 'rose-100', name: '100', value: '#FFDAE3', group: 'Secondary Colors', colorGroupName: 'rose' },
  { id: 'rose-200', name: '200', value: '#FFB5C6', group: 'Secondary Colors', colorGroupName: 'rose' },
  { id: 'rose-300', name: '300', value: '#FF90AA', group: 'Secondary Colors', colorGroupName: 'rose' },
  { id: 'rose-400', name: '400', value: '#FF6B8D', group: 'Secondary Colors', colorGroupName: 'rose' },
  { id: 'rose-500', name: '500', value: '#FF4671', group: 'Secondary Colors', colorGroupName: 'rose', isBase: true },
  { id: 'rose-600', name: '600', value: '#CC385A', group: 'Secondary Colors', colorGroupName: 'rose' },
  { id: 'rose-700', name: '700', value: '#992A44', group: 'Secondary Colors', colorGroupName: 'rose' },
  { id: 'rose-800', name: '800', value: '#661C2D', group: 'Secondary Colors', colorGroupName: 'rose' },
  { id: 'rose-900', name: '900', value: '#330E17', group: 'Secondary Colors', colorGroupName: 'rose' },

  { id: 'navy-50', name: '50', value: '#EAF8FB', group: 'Secondary Colors', colorGroupName: 'navy' },
  { id: 'navy-100', name: '100', value: '#D8EFF4', group: 'Secondary Colors', colorGroupName: 'navy' },
  { id: 'navy-200', name: '200', value: '#B2E2EB', group: 'Secondary Colors', colorGroupName: 'navy' },
  { id: 'navy-300', name: '300', value: '#9DDBE7', group: 'Secondary Colors', colorGroupName: 'navy' },
  { id: 'navy-400', name: '400', value: '#83D1E0', group: 'Secondary Colors', colorGroupName: 'navy' },
  { id: 'navy-500', name: '500', value: '#3ABED8', group: 'Secondary Colors', colorGroupName: 'navy', isBase: true },
  { id: 'navy-600', name: '600', value: '#1690A8', group: 'Secondary Colors', colorGroupName: 'navy' },
  { id: 'navy-700', name: '700', value: '#105F7E', group: 'Secondary Colors', colorGroupName: 'navy' },
  { id: 'navy-800', name: '800', value: '#193B5A', group: 'Secondary Colors', colorGroupName: 'navy' },
  { id: 'navy-900', name: '900', value: '#0C2943', group: 'Secondary Colors', colorGroupName: 'navy' },
]

// const menu = [
//   { name: 'Button', path: '/Button' },
//   { name: 'Button', path: '/Button' },
//   { name: 'Button', path: '/Button' },
//   { name: 'Button', path: '/Button' },
//   { name: 'Button', path: '/Button' },
//   { name: 'Button', path: '/Button' },
//   { name: 'Button', path: '/Button' },
//   { name: 'Button', path: '/Button' },
//   { name: 'Button', path: '/Button' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'Button', path: '/Button', group: 'Buttons' },
//   { name: 'IconButton', path: '/Button', group: 'Buttons' },
//   { name: 'SimpleButton', path: '/Button', group: 'Buttons' },
//   { name: 'CodePreview', path: '/CodePreview', group: 'Misc' },
// ]


const additionalPages = [
  {
    name: 'Colors',
    path: '/Colors',
    group: 'General',
    type: 'colors',
    index: 1,
    props: {
      options: colorOptions,
      description: 'A centralized color palette for the application, showcasing primary and secondary colors to ensure visual consistency across all interfaces.'
    }
  },
  {
    name: 'Icons',
    path: '/Icons',
    group: 'General',
    type: 'icons',
    index: 2,
    props: {
      options: iconComponents || [],
      configuration: iconConfig,
    }
  },
]

const menuGroupsDescription = {
  Buttons: 'Various button components with different styles and functionalities.',
  Misc: 'Miscellaneous components for various use cases.',
  General: 'General components information and guidelines.',
  Other: 'Components that do not fit into the above categories but are essential for the design system.',
}

createLab({ components, menuGroupsDescription, configuration, additionalPages })
  .mount('#app')
