import { createLab } from './index'
import * as components from './components'
import configuration from './components/vuelab-configs/index.js'

const menu = [
  { name: 'Button', path: '/Button' },
  { name: 'Button', path: '/Button' },
  { name: 'Button', path: '/Button' },
  { name: 'Button', path: '/Button' },
  { name: 'Button', path: '/Button' },
  { name: 'Button', path: '/Button' },
  { name: 'Button', path: '/Button' },
  { name: 'Button', path: '/Button' },
  { name: 'Button', path: '/Button' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'Button', path: '/Button', group: 'Buttons' },
  { name: 'IconButton', path: '/Button', group: 'Buttons' },
  { name: 'SimpleButton', path: '/Button', group: 'Buttons' },
  { name: 'CodePreview', path: '/CodePreview', group: 'Misc' },
]

const menuGroupsDescription = {
  Buttons: 'Various button components with different styles and functionalities.',
  Misc: 'Miscellaneous components for various use cases.',
}

createLab({ components, menu, menuGroupsDescription, configuration })
  .mount('#app')
